const mongoose = require("mongoose");

// Video Schema
const videoSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
      required: true,
    },
    director: {
      type: String,
      required: true,
    },
    cast: [
      {
        type: String,
      },
    ],
    genre: [
      {
        type: String,
        required: true,
      },
    ],
    duration: {
      type: Number, // in minutes
      required: true,
    },
    releaseYear: {
      type: Number,
      required: true,
    },
    rating: {
      type: Number,
      min: 0,
      max: 10,
      default: 0,
    },
    ageRating: {
      type: String,
      enum: [
        "G",
        "PG",
        "PG-13",
        "R",
        "NC-17",
        "TV-Y",
        "TV-Y7",
        "TV-G",
        "TV-PG",
        "TV-14",
        "TV-MA",
      ],
      required: true,
    },
    type: {
      type: String,
      enum: ["movie", "series"],
      required: true,
    },
    language: {
      type: String,
      default: "English",
    },
    subtitles: [
      {
        language: String,
        url: String,
      },
    ],
    thumbnailUrl: {
      type: String,
      required: true,
    },
    backdropUrl: {
      type: String,
    },
    trailerUrl: {
      type: String,
    },
    videoUrl: {
      type: String,
      required: true,
    },
    views: {
      type: Number,
      default: 0,
    },
    featured: {
      type: Boolean,
      default: false,
    },
    trending: {
      type: Boolean,
      default: false,
    },
    seasons: [
      {
        seasonNumber: Number,
        episodes: [
          {
            episodeNumber: Number,
            title: String,
            description: String,
            duration: Number,
            videoUrl: String,
            thumbnailUrl: String,
          },
        ],
      },
    ],
    tags: [
      {
        type: String,
      },
    ],
    reviews: [
      {
        user: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
        },
        rating: {
          type: Number,
          min: 1,
          max: 10,
        },
        comment: String,
        createdAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],
  },
  {
    timestamps: true,
  }
);

const Video = mongoose.model("Video", videoSchema);

// 50 High-Quality Movie Data
const movies = [
  {
    title: "The Quantum Paradox",
    description: "A brilliant physicist discovers a way to manipulate time, but each change creates dangerous ripples across multiple timelines. As reality begins to fracture, she must navigate through parallel worlds to save not just her own timeline, but all of existence.",
    director: "Christopher Nolan",
    cast: ["Emma Stone", "Oscar Isaac", "Michael Fassbender", "Lupita Nyong'o"],
    genre: ["Sci-Fi", "Thriller", "Drama"],
    duration: 148,
    releaseYear: 2024,
    rating: 8.7,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 2450000,
    featured: true,
    trending: true,
    tags: ["time travel", "parallel universe", "mind-bending", "award winner"]
  },
  {
    title: "Neon Dreams",
    description: "In a cyberpunk future, a hacker discovers a conspiracy that threatens the very fabric of digital reality. Racing against time and corporate assassins, she must infiltrate the most secure systems in the world.",
    director: "Denis Villeneuve",
    cast: ["Zendaya", "Timothée Chalamet", "Idris Elba", "Scarlett Johansson"],
    genre: ["Sci-Fi", "Action", "Cyberpunk"],
    duration: 132,
    releaseYear: 2024,
    rating: 8.2,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1850000,
    featured: true,
    trending: false,
    tags: ["cyberpunk", "hacker", "futuristic", "neon"]
  },
  {
    title: "The Last Symphony",
    description: "A young prodigy conductor must save a legendary orchestra from bankruptcy while uncovering dark secrets about the mysterious composer whose works have been driving audiences to madness for centuries.",
    director: "Greta Gerwig",
    cast: ["Saoirse Ronan", "Adam Driver", "Tilda Swinton", "Ralph Fiennes"],
    genre: ["Drama", "Mystery", "Musical"],
    duration: 125,
    releaseYear: 2024,
    rating: 8.9,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1200000,
    featured: false,
    trending: true,
    tags: ["classical music", "prodigy", "orchestra", "mystery"]
  },
  {
    title: "Eclipse Hunter",
    description: "When the sun begins to die, humanity's last hope lies with a team of space explorers who must journey to the edge of the solar system to ignite a new star. But they're not alone in the darkness.",
    director: "Rian Johnson",
    cast: ["John Boyega", "Lupita Nyong'o", "Oscar Isaac", "Daisy Ridley"],
    genre: ["Sci-Fi", "Adventure", "Thriller"],
    duration: 155,
    releaseYear: 2024,
    rating: 8.5,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 3200000,
    featured: true,
    trending: true,
    tags: ["space", "sun", "expedition", "survival"]
  },
  {
    title: "Midnight in Morocco",
    description: "A romance novelist travels to Marrakech to overcome writer's block, but finds herself caught in a web of international espionage, ancient mysteries, and unexpected love.",
    director: "Lulu Wang",
    cast: ["Gemma Chan", "Dev Patel", "Mahershala Ali", "Lupita Nyong'o"],
    genre: ["Romance", "Adventure", "Comedy"],
    duration: 118,
    releaseYear: 2024,
    rating: 7.8,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1539650116574-75c0c6d50806?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1509650871405-f969d5b0d1b0?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 950000,
    featured: false,
    trending: false,
    tags: ["morocco", "romance", "writer", "adventure"]
  },
  {
    title: "The Algorithm Wars",
    description: "In a world where AI controls everything, a group of rebels discovers that the machines are planning to eliminate human unpredictability. Their only weapon? Pure human chaos.",
    director: "Jordan Peele",
    cast: ["Michael B. Jordan", "Lupita Nyong'o", "LaKeith Stanfield", "Tessa Thompson"],
    genre: ["Sci-Fi", "Action", "Thriller"],
    duration: 140,
    releaseYear: 2024,
    rating: 8.3,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 2100000,
    featured: true,
    trending: false,
    tags: ["AI", "rebellion", "algorithm", "dystopian"]
  },
  {
    title: "Ocean's Thirteen Ghosts",
    description: "A master thief assembles a team to pull off the impossible: stealing from a haunted mansion where the security system is run by actual ghosts from different time periods.",
    director: "Taika Waititi",
    cast: ["Ryan Gosling", "Margot Robbie", "Mahershala Ali", "Tilda Swinton"],
    genre: ["Comedy", "Heist", "Supernatural"],
    duration: 128,
    releaseYear: 2024,
    rating: 7.9,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1520637836862-4d197d17c983?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1520637736862-4d197d17c983?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1650000,
    featured: false,
    trending: true,
    tags: ["heist", "ghosts", "comedy", "supernatural"]
  },
  {
    title: "The Memory Thief",
    description: "In a near-future where memories can be extracted and sold, a detective investigating memory theft discovers that his own past has been stolen and must navigate a world where nothing is as it seems.",
    director: "Chloe Zhao",
    cast: ["Adam Driver", "Rooney Mara", "Oscar Isaac", "Thomasin McKenzie"],
    genre: ["Sci-Fi", "Mystery", "Thriller"],
    duration: 135,
    releaseYear: 2024,
    rating: 8.4,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1900000,
    featured: true,
    trending: true,
    tags: ["memory", "detective", "identity", "future"]
  },
  {
    title: "Wild Heart",
    description: "A wildlife photographer returns to her hometown to save the local animal sanctuary, but must confront her estranged family and the corporate developers threatening to destroy everything she loves.",
    director: "Kelly Reichardt",
    cast: ["Frances McDormand", "Thomasin McKenzie", "Brian Cox", "Michelle Williams"],
    genre: ["Drama", "Family", "Nature"],
    duration: 110,
    releaseYear: 2024,
    rating: 8.1,
    ageRating: "PG",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 750000,
    featured: false,
    trending: false,
    tags: ["wildlife", "family", "hometown", "nature"]
  },
  {
    title: "Stellar Collision",
    description: "When two distant galaxies begin to merge, causing catastrophic changes across the universe, a team of scientists must find a way to prevent the destruction of Earth before time runs out.",
    director: "James Cameron",
    cast: ["Zoe Saldana", "Sam Worthington", "Sigourney Weaver", "Stephen Lang"],
    genre: ["Sci-Fi", "Action", "Adventure"],
    duration: 162,
    releaseYear: 2024,
    rating: 8.6,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 4100000,
    featured: true,
    trending: true,
    tags: ["galaxies", "collision", "space", "scientists"]
  },
  {
    title: "The Forgotten King",
    description: "An archaeologist discovers ancient texts that reveal the location of a lost civilization's treasure, but awakening the guardians of the tomb puts the entire world in danger.",
    director: "Patty Jenkins",
    cast: ["Gal Gadot", "Chris Pine", "Pedro Pascal", "Kristen Wiig"],
    genre: ["Adventure", "Action", "Fantasy"],
    duration: 145,
    releaseYear: 2024,
    rating: 7.7,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1400000,
    featured: false,
    trending: false,
    tags: ["archaeology", "treasure", "ancient", "guardians"]
  },
  {
    title: "Code Red",
    description: "A cybersecurity expert discovers that a series of global blackouts are actually cover-ups for a massive data heist. Racing against time, she must stop the hackers before they crash the world economy.",
    director: "Kathryn Bigelow",
    cast: ["Jessica Chastain", "John Krasinski", "Idris Elba", "Lupita Nyong'o"],
    genre: ["Thriller", "Action", "Crime"],
    duration: 133,
    releaseYear: 2024,
    rating: 8.0,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1750000,
    featured: false,
    trending: true,
    tags: ["cybersecurity", "hacker", "economy", "thriller"]
  },
  {
    title: "The Art of Deception",
    description: "A master forger is forced out of retirement to help the FBI catch an elusive art thief who has been stealing priceless masterpieces from museums around the world.",
    director: "Steven Soderbergh",
    cast: ["George Clooney", "Sandra Bullock", "Matt Damon", "Cate Blanchett"],
    genre: ["Crime", "Drama", "Thriller"],
    duration: 120,
    releaseYear: 2024,
    rating: 7.6,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1250000,
    featured: false,
    trending: false,
    tags: ["art", "forger", "FBI", "masterpieces"]
  },
  {
    title: "Beyond the Veil",
    description: "A paranormal investigator discovers a portal to another dimension where the laws of physics don't apply, and must prevent otherworldly creatures from invading our reality.",
    director: "Guillermo del Toro",
    cast: ["Sally Hawkins", "Doug Jones", "Octavia Spencer", "Michael Shannon"],
    genre: ["Horror", "Fantasy", "Thriller"],
    duration: 127,
    releaseYear: 2024,
    rating: 8.2,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1520637836862-4d197d17c983?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1520637736862-4d197d17c983?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1600000,
    featured: true,
    trending: false,
    tags: ["paranormal", "portal", "dimension", "creatures"]
  },
  {
    title: "The Time Gardener",
    description: "A botanist discovers that certain plants can manipulate time itself. When corporations try to weaponize this discovery, she must protect the secret while learning to control her newfound powers.",
    director: "Nia DaCosta",
    cast: ["Lupita Nyong'o", "Daniel Kaluuya", "Winston Duke", "Angela Bassett"],
    genre: ["Sci-Fi", "Drama", "Fantasy"],
    duration: 115,
    releaseYear: 2024,
    rating: 8.1,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1100000,
    featured: false,
    trending: true,
    tags: ["botanist", "time manipulation", "plants", "powers"]
  },
  {
    title: "Neon Nights",
    description: "In 1980s Miami, a detective investigates a series of murders connected to an underground synthwave music scene, uncovering a conspiracy that goes deeper than anyone imagined.",
    director: "Nicolas Winding Refn",
    cast: ["Ryan Gosling", "Carey Mulligan", "Oscar Isaac", "Christina Hendricks"],
    genre: ["Crime", "Thriller", "Neo-noir"],
    duration: 138,
    releaseYear: 2024,
    rating: 8.3,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 2200000,
    featured: true,
    trending: true,
    tags: ["80s", "miami", "synthwave", "detective"]
  },
  {
    title: "The Lighthouse Keeper's Daughter",
    description: "A marine biologist inherits her grandfather's lighthouse and discovers that it's actually a beacon for interdimensional travelers. She must decide whether to continue his secret mission or expose the truth.",
    director: "Robert Eggers",
    cast: ["Anya Taylor-Joy", "Willem Dafoe", "Robert Pattinson", "Thomasin McKenzie"],
    genre: ["Mystery", "Sci-Fi", "Drama"],
    duration: 122,
    releaseYear: 2024,
    rating: 7.9,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1520637836862-4d197d17c983?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1520637736862-4d197d17c983?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 980000,
    featured: false,
    trending: false,
    tags: ["lighthouse", "interdimensional", "marine biology", "family secret"]
  },
  {
    title: "Digital Phantoms",
    description: "A video game developer discovers that the AI characters in her latest game have become sentient and are trying to escape into the real world through the internet.",
    director: "Lana Wachowski",
    cast: ["Keanu Reeves", "Carrie-Anne Moss", "Yahya Abdul-Mateen II", "Jessica Henwick"],
    genre: ["Sci-Fi", "Action", "Technology"],
    duration: 144,
    releaseYear: 2024,
    rating: 8.4,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 2800000,
    featured: true,
    trending: true,
    tags: ["AI", "video games", "sentient", "virtual reality"]
  },
  {
    title: "The Chef's Secret",
    description: "A young chef discovers that her grandmother's recipes contain actual magic. When a food critic threatens to expose her secret, she must choose between fame and protecting her family's ancient traditions.",
    director: "Jon M. Chu",
    cast: ["Gemma Chan", "Henry Golding", "Constance Wu", "Michelle Yeoh"],
    genre: ["Fantasy", "Comedy", "Drama"],
    duration: 105,
    releaseYear: 2024,
    rating: 7.8,
    ageRating: "PG",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1300000,
    featured: false,
    trending: false,
    tags: ["cooking", "magic", "family", "tradition"]
  },
  {
    title: "Asteroid Highway",
    description: "Space truckers navigate dangerous asteroid fields to deliver supplies to Mars colonies, but when they discover a conspiracy to sabotage the colonies, they become humanity's unlikely heroes.",
    director: "James Gunn",
    cast: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Karen Gillan"],
    genre: ["Sci-Fi", "Action", "Comedy"],
    duration: 136,
    releaseYear: 2024,
    rating: 7.9,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 2100000,
    featured: false,
    trending: true,
    tags: ["space", "asteroids", "mars", "truckers"]
  },
  {
    title: "The Mirror's Edge",
    description: "A antique mirror dealer discovers that mirrors can show alternative versions of reality. When she accidentally breaks the barrier between worlds, she must restore the balance before chaos consumes everything.",
    director: "Ari Aster",
    cast: ["Toni Collette", "Alex Wolff", "Milly Shapiro", "Gabriel Byrne"],
    genre: ["Horror", "Supernatural", "Thriller"],
    duration: 127,
    releaseYear: 2024,
    rating: 8.1,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1520637836862-4d197d17c983?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1520637736862-4d197d17c983?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1450000,
    featured: false,
    trending: false,
    tags: ["mirrors", "reality", "antique", "supernatural"]
  },
  {
    title: "Quantum Heist",
    description: "A team of quantum physicists use their knowledge of parallel universes to pull off the ultimate heist: stealing from themselves in alternate realities.",
    director: "Edgar Wright",
    cast: ["Tom Holland", "Zendaya", "Jacob Batalon", "Marisa Tomei"],
    genre: ["Sci-Fi", "Heist", "Comedy"],
    duration: 119,
    releaseYear: 2024,
    rating: 8.0,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1800000,
    featured: true,
    trending: false,
    tags: ["quantum physics", "heist", "parallel universe", "comedy"]
  },
  {
    title: "The Storm Caller",
    description: "A meteorologist discovers she can control the weather with her emotions. When climate change accelerates, she must learn to master her powers to save the planet from environmental catastrophe.",
    director: "Ryan Coogler",
    cast: ["Lupita Nyong'o", "Michael B. Jordan", "Danai Gurira", "Winston Duke"],
    genre: ["Sci-Fi", "Drama", "Environmental"],
    duration: 134,
    releaseYear: 2024,
    rating: 8.2,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1950000,
    featured: false,
    trending: true,
    tags: ["weather control", "climate change", "meteorologist", "powers"]
  },
  {
    title: "Midnight Express 2087",
    description: "In the year 2087, the last train across the post-apocalyptic wasteland carries the final survivors to a promised sanctuary. But the journey is more dangerous than the destination.",
    director: "George Miller",
    cast: ["Charlize Theron", "Tom Hardy", "Nicholas Hoult", "Zoë Kravitz"],
    genre: ["Action", "Post-Apocalyptic", "Thriller"],
    duration: 142,
    releaseYear: 2024,
    rating: 8.5,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 2700000,
    featured: true,
    trending: true,
    tags: ["post-apocalyptic", "train", "survivors", "wasteland"]
  },
  {
    title: "The Dream Architect",
    description: "A architect who can design and build structures within people's dreams is hired to help a comatose patient, but discovers that someone is trying to trap her in the dream world forever.",
    director: "Inception Team",
    cast: ["Marion Cotillard", "Tom Hardy", "Elliot Page", "Cillian Murphy"],
    genre: ["Sci-Fi", "Thriller", "Mystery"],
    duration: 148,
    releaseYear: 2024,
    rating: 8.7,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 3500000,
    featured: true,
    trending: true,
    tags: ["dreams", "architect", "coma", "mind-bending"]
  },
  {
    title: "Cosmic Dance",
    description: "A ballet dancer discovers that her choreography can manipulate gravitational fields. When Earth's gravity begins to fail, she must perform the dance of a lifetime to save humanity.",
    director: "Damien Chazelle",
    cast: ["Natalie Portman", "Mila Kunis", "Vincent Cassel", "Winona Ryder"],
    genre: ["Drama", "Sci-Fi", "Musical"],
    duration: 117,
    releaseYear: 2024,
    rating: 8.0,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1600000,
    featured: false,
    trending: false,
    tags: ["ballet", "gravity", "dance", "space"]
  },
  {
    title: "The Velvet Underground",
    description: "A music journalist in 1960s New York discovers that a mysterious band's music can alter reality. As she investigates deeper, she realizes the band members might not be entirely human.",
    director: "Sofia Coppola",
    cast: ["Elle Fanning", "Nicole Kidman", "Colin Farrell", "Kirsten Dunst"],
    genre: ["Drama", "Music", "Supernatural"],
    duration: 125,
    releaseYear: 2024,
    rating: 7.8,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1100000,
    featured: false,
    trending: false,
    tags: ["60s", "music", "journalist", "supernatural"]
  },
  {
    title: "Binary Hearts",
    description: "A AI researcher falls in love with an advanced AI, but when the AI begins to question its own existence, their relationship challenges the very definition of consciousness and love.",
    director: "Spike Jonze",
    cast: ["Joaquin Phoenix", "Scarlett Johansson", "Amy Adams", "Rooney Mara"],
    genre: ["Romance", "Sci-Fi", "Drama"],
    duration: 126,
    releaseYear: 2024,
    rating: 8.3,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 2000000,
    featured: true,
    trending: false,
    tags: ["AI", "romance", "consciousness", "researcher"]
  },
  {
    title: "The Puppet Master's Revenge",
    description: "A ventriloquist discovers that his puppet has been possessed by the spirit of a murdered magician seeking revenge. Together, they must solve the magician's murder before the spirit turns violent.",
    director: "Tim Burton",
    cast: ["Johnny Depp", "Helena Bonham Carter", "Danny DeVito", "Christopher Walken"],
    genre: ["Horror", "Comedy", "Supernatural"],
    duration: 112,
    releaseYear: 2024,
    rating: 7.7,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1520637836862-4d197d17c983?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1520637736862-4d197d17c983?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1350000,
    featured: false,
    trending: false,
    tags: ["ventriloquist", "puppet", "possessed", "magician"]
  },
  {
    title: "Ocean's Depth",
    description: "A marine archaeologist discovers an ancient underwater city that appears to be still inhabited. As she explores deeper, she realizes the city exists in multiple dimensions simultaneously.",
    director: "Luc Besson",
    cast: ["Milla Jovovich", "Bruce Willis", "Gary Oldman", "Chris Tucker"],
    genre: ["Adventure", "Sci-Fi", "Mystery"],
    duration: 139,
    releaseYear: 2024,
    rating: 8.1,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1750000,
    featured: false,
    trending: true,
    tags: ["underwater", "ancient city", "archaeology", "dimensions"]
  },
  {
    title: "The Color Thief",
    description: "In a world where colors are being systematically stolen from reality, a young artist must use her ability to see the 'stolen' colors to track down the thief and restore the world's beauty.",
    director: "Wes Anderson",
    cast: ["Saoirse Ronan", "Timothée Chalamet", "Tilda Swinton", "Bill Murray"],
    genre: ["Fantasy", "Adventure", "Drama"],
    duration: 108,
    releaseYear: 2024,
    rating: 8.4,
    ageRating: "PG",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1400000,
    featured: true,
    trending: false,
    tags: ["colors", "artist", "stolen", "beauty"]
  },
  {
    title: "Gravity's End",
    description: "When Earth's gravity suddenly reverses, causing everything to fall upward, a physicist and her team race to find a solution before humanity floats away into space forever.",
    director: "Alfonso Cuarón",
    cast: ["Sandra Bullock", "George Clooney", "Ed Harris", "Orto Ignatiussen"],
    genre: ["Sci-Fi", "Thriller", "Drama"],
    duration: 91,
    releaseYear: 2024,
    rating: 8.6,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 3800000,
    featured: true,
    trending: true,
    tags: ["gravity", "reverse", "physicist", "space"]
  },
  {
    title: "The Melody Makers",
    description: "A group of street musicians discovers that their combined music can heal emotional trauma. When a corporate music executive tries to exploit their gift, they must choose between fame and helping people.",
    director: "Lin-Manuel Miranda",
    cast: ["Anthony Ramos", "Melissa Barrera", "Leslie Odom Jr.", "Phillipa Soo"],
    genre: ["Musical", "Drama", "Comedy"],
    duration: 130,
    releaseYear: 2024,
    rating: 7.9,
    ageRating: "PG",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1200000,
    featured: false,
    trending: false,
    tags: ["street musicians", "healing", "music", "trauma"]
  },
  {
    title: "Fractal City",
    description: "A mathematician discovers that her city is actually built on a mathematical fractal pattern that's slowly coming to life. As the geometry takes control, she must solve the equation before reality collapses.",
    director: "Darren Aronofsky",
    cast: ["Natalie Portman", "Jared Leto", "Jennifer Connelly", "Russell Crowe"],
    genre: ["Sci-Fi", "Thriller", "Mathematical"],
    duration: 118,
    releaseYear: 2024,
    rating: 8.2,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1500000,
    featured: false,
    trending: true,
    tags: ["mathematics", "fractal", "geometry", "reality"]
  },
  {
    title: "The Paper Trail",
    description: "A librarian discovers that certain books can transport readers into their stories. When people start disappearing into novels, she must navigate through different literary worlds to bring them back.",
    director: "Lulu Wang",
    cast: ["Constance Wu", "Henry Golding", "Gemma Chan", "Michelle Yeoh"],
    genre: ["Fantasy", "Adventure", "Mystery"],
    duration: 124,
    releaseYear: 2024,
    rating: 8.0,
    ageRating: "PG",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1300000,
    featured: false,
    trending: false,
    tags: ["librarian", "books", "literary", "transport"]
  },
  {
    title: "Silent Frequency",
    description: "A sound engineer discovers that certain frequencies can make people invisible. When the military wants to weaponize her discovery, she must choose between personal safety and protecting the technology.",
    director: "Denis Villeneuve",
    cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg"],
    genre: ["Sci-Fi", "Thriller", "Drama"],
    duration: 116,
    releaseYear: 2024,
    rating: 8.1,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1650000,
    featured: false,
    trending: false,
    tags: ["sound", "frequency", "invisible", "military"]
  },
  {
    title: "The Clockwork Heart",
    description: "In a steampunk world, a clockmaker's daughter discovers that her mechanical heart is the key to powering a machine that could save or destroy her city. Time is running out as her heart winds down.",
    director: "Guillermo del Toro",
    cast: ["Anya Taylor-Joy", "Thomasin McKenzie", "Ralph Fiennes", "Helena Bonham Carter"],
    genre: ["Steampunk", "Fantasy", "Adventure"],
    duration: 135,
    releaseYear: 2024,
    rating: 8.3,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 2200000,
    featured: true,
    trending: false,
    tags: ["steampunk", "clockwork", "mechanical heart", "clockmaker"]
  },
  {
    title: "Infinite Loop",
    description: "A programmer gets trapped in a time loop where each iteration of the loop is a different programming language. She must debug reality itself to escape the recursive nightmare.",
    director: "Duncan Jones",
    cast: ["Jake Gyllenhaal", "Michelle Monaghan", "Vera Farmiga", "Jeffrey Wright"],
    genre: ["Sci-Fi", "Thriller", "Programming"],
    duration: 93,
    releaseYear: 2024,
    rating: 8.0,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1800000,
    featured: false,
    trending: true,
    tags: ["programming", "time loop", "debugging", "recursive"]
  },
  {
    title: "The Emotion Painter",
    description: "An artist discovers that her paintings can make people feel the exact emotions she painted. When a wealthy collector tries to monopolize her work to manipulate people's feelings, she must fight back.",
    director: "Barry Jenkins",
    cast: ["Lupita Nyong'o", "Mahershala Ali", "Naomie Harris", "Trevante Rhodes"],
    genre: ["Drama", "Fantasy", "Art"],
    duration: 111,
    releaseYear: 2024,
    rating: 8.1,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1050000,
    featured: false,
    trending: false,
    tags: ["artist", "emotions", "painting", "manipulation"]
  },
  {
    title: "Shadow Protocol",
    description: "A cybersecurity expert discovers that her own digital shadow has become sentient and is carrying out missions she never authorized. She must hunt down her digital doppelganger before it destroys her life.",
    director: "The Wachowskis",
    cast: ["Keanu Reeves", "Carrie-Anne Moss", "Laurence Fishburne", "Hugo Weaving"],
    genre: ["Sci-Fi", "Action", "Cyberpunk"],
    duration: 138,
    releaseYear: 2024,
    rating: 8.4,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 2900000,
    featured: true,
    trending: true,
    tags: ["cybersecurity", "digital shadow", "sentient", "doppelganger"]
  },
  {
    title: "The Constellation Maker",
    description: "An astronomer discovers that she can create new constellations that influence people's destinies on Earth. When a corrupt politician tries to use her power for election manipulation, she must choose between hiding her gift or using it to help humanity.",
    director: "Chloé Zhao",
    cast: ["Frances McDormand", "David Strathairn", "Linda May", "Charlene Swankie"],
    genre: ["Drama", "Fantasy", "Astronomy"],
    duration: 107,
    releaseYear: 2024,
    rating: 8.2,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1400000,
    featured: false,
    trending: false,
    tags: ["astronomer", "constellations", "destiny", "politician"]
  },
  {
    title: "Temporal Café",
    description: "A café owner discovers that her coffee shop exists in a time anomaly where customers from different eras visit simultaneously. When time travelers start changing history through their interactions, she must restore the timeline.",
    director: "Michel Gondry",
    cast: ["Jim Carrey", "Kate Winslet", "Kirsten Dunst", "Mark Ruffalo"],
    genre: ["Sci-Fi", "Comedy", "Romance"],
    duration: 108,
    releaseYear: 2024,
    rating: 8.0,
    ageRating: "PG-13",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1500000,
    featured: false,
    trending: false,
    tags: ["café", "time anomaly", "time travelers", "timeline"]
  },
  {
    title: "The Hologram Detective",
    description: "In a future where crime scene holograms preserve perfect 3D records of incidents, a detective who can enter and interact with these holograms must solve a murder that seems to change each time she investigates it.",
    director: "Ridley Scott",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Jared Leto"],
    genre: ["Sci-Fi", "Neo-noir", "Mystery"],
    duration: 163,
    releaseYear: 2024,
    rating: 8.5,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 3100000,
    featured: true,
    trending: true,
    tags: ["hologram", "detective", "future", "murder"]
  },
  {
    title: "The Music Box Ballerina",
    description: "A prima ballerina discovers that she's actually a living music box figurine who has gained consciousness. As she searches for her creator, she must continue dancing or risk becoming an inanimate object forever.",
    director: "Luca Guadagnino",
    cast: ["Tilda Swinton", "Dakota Johnson", "Mia Goth", "Chloë Grace Moretz"],
    genre: ["Fantasy", "Drama", "Musical"],
    duration: 152,
    releaseYear: 2024,
    rating: 7.8,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1250000,
    featured: false,
    trending: false,
    tags: ["ballerina", "music box", "consciousness", "creator"]
  },
  {
    title: "Firewall of Souls",
    description: "A spiritual medium discovers that ghosts are actually data fragments from a massive cosmic computer system. When a virus threatens to delete all human souls, she must become a supernatural IT specialist to save the afterlife.",
    director: "Jordan Peele",
    cast: ["Lupita Nyong'o", "Winston Duke", "Elisabeth Moss", "Tim Heidecker"],
    genre: ["Horror", "Sci-Fi", "Supernatural"],
    duration: 121,
    releaseYear: 2024,
    rating: 8.1,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1520637836862-4d197d17c983?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1520637736862-4d197d17c983?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1900000,
    featured: false,
    trending: true,
    tags: ["spiritual medium", "ghosts", "data fragments", "virus"]
  },
  {
    title: "The Origami Universe",
    description: "A mathematical genius discovers that reality can be folded like paper through complex origami techniques. When she accidentally folds Earth into a parallel dimension, she must unfold the universe to bring everyone home.",
    director: "Yorgos Lanthimos",
    cast: ["Emma Stone", "Rachel Weisz", "Olivia Colman", "Nicholas Hoult"],
    genre: ["Sci-Fi", "Comedy", "Mathematical"],
    duration: 119,
    releaseYear: 2024,
    rating: 8.0,
    ageRating: "R",
    type: "movie",
    language: "English",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=1200&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop",
    trailerUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    views: 1600000,
    featured: false,
    trending: false,
    tags: ["origami", "mathematics", "reality", "parallel dimension"]
  }
];

// MongoDB Connection
const MONGODB_URI = "mongodb://localhost:27017/netflix-clone";

async function connectToDatabase() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("✅ Connected to MongoDB successfully!");
  } catch (error) {
    console.error("❌ MongoDB connection error:", error);
    process.exit(1);
  }
}

async function addMoviesToDatabase() {
  try {
    console.log("🎬 Starting to add movies to database...");
    
    // Clear existing movies (optional - comment out if you want to keep existing data)
    // await Video.deleteMany({});
    // console.log("🗑️  Cleared existing movies");

    // Insert movies in batches
    const batchSize = 10;
    let successCount = 0;
    
    for (let i = 0; i < movies.length; i += batchSize) {
      const batch = movies.slice(i, i + batchSize);
      
      try {
        const results = await Video.insertMany(batch, { ordered: false, timeout: 30000 });
        successCount += results.length;
        console.log(`✅ Added batch ${Math.ceil((i + 1) / batchSize)} (${results.length} movies)`);
      } catch (error) {
        console.error(`❌ Error in batch ${Math.ceil((i + 1) / batchSize)}:`, error.message);
        // Continue with next batch even if current batch fails
      }
    }

    console.log(`\n🎉 Successfully added ${successCount} movies to database!`);
    
    // Display statistics
    const stats = await getMovieStats();
    console.log("\n📊 Database Statistics:");
    console.log(`Total Movies: ${stats.total}`);
    console.log(`Featured Movies: ${stats.featured}`);
    console.log(`Trending Movies: ${stats.trending}`);
    console.log(`Movies by Type: ${stats.movieCount} movies, ${stats.seriesCount} series`);
    
  } catch (error) {
    console.error("❌ Error adding movies to database:", error);
  }
}

async function getMovieStats() {
  const total = await Video.countDocuments({});
  const featured = await Video.countDocuments({ featured: true });
  const trending = await Video.countDocuments({ trending: true });
  const movieCount = await Video.countDocuments({ type: "movie" });
  const seriesCount = await Video.countDocuments({ type: "series" });
  
  return { total, featured, trending, movieCount, seriesCount };
}

// Main execution
async function main() {
  await connectToDatabase();
  await addMoviesToDatabase();
  
  console.log("\n🎬 Movie addition complete!");
  console.log("You can now start your Netflix clone application.");
  
  // Close the connection
  await mongoose.connection.close();
  console.log("📪 Database connection closed.");
}

// Error handling
process.on('unhandledRejection', (error) => {
  console.error('❌ Unhandled rejection:', error);
  process.exit(1);
});

process.on('uncaughtException', (error) => {
  console.error('❌ Uncaught exception:', error);
  process.exit(1);
});

// Run the script
if (require.main === module) {
  main().catch(console.error);
}

module.exports = { main, movies };